/**
 * Firefox manifest sync — manifest.firefox.json vs manifest.json
 *
 * CNAME uncloaking (Firefox-only) needs dns + webRequest + webRequestBlocking,
 * which Chrome stable rejects. manifest.json stays Chrome-clean; the Firefox build
 * (manifest.firefox.json, generated by tools/build-firefox.mjs) adds them as
 * optional_permissions. These tests keep the two in lockstep.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const chrome = JSON.parse(readFileSync(`${ROOT}manifest.json`, 'utf8'));
const fox = JSON.parse(readFileSync(`${ROOT}manifest.firefox.json`, 'utf8'));

test('Firefox manifest carries the CNAME optional permissions', () => {
  assert.deepEqual(fox.optional_permissions, ['dns', 'webRequest', 'webRequestBlocking']);
});

test('Firefox manifest equals the Chrome manifest plus optional_permissions', () => {
  const copy = { ...fox };
  delete copy.optional_permissions;
  // If this fails, regenerate: node tools/build-firefox.mjs
  assert.deepEqual(copy, chrome);
});

test('Chrome manifest stays free of the Firefox-only permissions', () => {
  const all = new Set([...(chrome.permissions || []), ...(chrome.optional_permissions || [])]);
  for (const p of ['dns', 'webRequestBlocking']) {
    assert.ok(!all.has(p), `${p} must not be in the Chrome manifest`);
  }
});
